# Generated by Django 4.0.4 on 2022-06-19 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('level', models.IntegerField(choices=[(1, '1 - Fundamental Awareness'), (2, '2 - Novice'), (3, '3 - Intermediate'), (4, '4 - Advanced'), (5, '5 - Expert')], default=1, verbose_name='Skill Level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
