# Generated by Django 4.0.4 on 2022-11-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='', max_length=250),
        ),
    ]
