# Generated by Django 4.0.4 on 2022-11-16 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_alter_note_content_note_unique content for each user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique content for each user',
        ),
        migrations.RemoveConstraint(
            model_name='skill',
            name='unique description for each user',
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('content', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('description', 'user')},
        ),
    ]
